### Listar todas as tarefas
GET http://localhost:5000/api/chamado/listar

### Cadastrar uma nova tarefa
POST http://localhost:5000/api/chamado/cadastrar
Content-Type: application/json

{
    "descricao": "TESTE 6"
}

### Atualizar
PUT http://localhost:5000/api/chamado/alterar/5eb94cd6-54d5-40fb-b3ce-e27b8a322e31
Content-Type: application/json

{
    "status" : "alterar"
}

### Chamados em aberto
GET http://localhost:5000/api/chamado/naoresolvidos